### ISSUE TITLE
from scatch

### ISSUE THREAD

**Issue by defong** [chef-cookbooks/nginx#292]
using chef/ubuntu-14.04

issue

when you just do 

```
chef.run_list = [
  "recipe[nginx::default]"
]
```

which is like sudo apt-get install nginx 

it spins up nginx on localhost:80 

but the nginx.pid is never created
you can find the pid using 
ps aux | grep nginx

which in turns leading to 
sudo service nginx status 
displaying its as not running

or any sudo service nginx cmd
as not working as port 80 is already binded

no default file is made for 
/var/www/nginx-default/index.html

more of a annoyance then anything else as i was just trying to get my head around chef and nginx

**Comment by lightpriest** [comment]
This happened to me as well. When nginx is installed from the normal Ubuntu repositores, it comes with pid path set to `/run/nginx.pid`. The package starts the service, then the cookbook changes the files so that the pid path is now `/var/run/nginx.pid`.

It causes `/etc/init.d/nginx` to lose track of the pid file that actually references the running nginx instance at install time.

There are two ways to work around the issue in a clean way:

1. As stated by @boffbowsh, including `recipe[nginx::repo]` in the run_list.
2. Changing the attribute `node['nginx']['pid']` if you want to continue using nginx packages from the official dist repo.

**Comment by austburn** [comment]
Seems like a fix for this might just be updating [this](https://github.com/miketheman/nginx/blob/master/attributes/default.rb#L43) to be:
```
if platform == 'ubuntu'
   default['nginx']['pid'] = '/run/nginx.pid'
end
```

**Comment by rmoriz** [comment]
fix from https://github.com/miketheman/nginx/commit/d2b954ef0507f3d458f5d7a5ced38f1ffcbf303b  should be more generic and support later versions. Any volunteers which find out, when Ubuntu started to change it?

**Comment by lightpriest** [comment]
@rmoriz Looks like it appeared in 13.04 raring (nginx-common = 1.2.6-1ubuntu3.3). Prior to that, nginx-common <= 1.2.1, used /var/run/nginx.pid.

**Comment by iennae** [comment]
I think that this was resolved. If it's still a problem with the current version of the cookbook please reopen with additional details.
