### ISSUE TITLE
Versioning doesn't work with install from source unless default

### ISSUE THREAD

**Issue by duncanphillips** [chef-cookbooks/nginx#307]
[ version woes ]

If you don't use the default version, then there is a race condition where the cookbook sets all other attributes based on the default version, not the user specified version. To fix, can either delete /opt/nginx\* and run chef again, or set attributes again manually.

**Comment by dieend** [comment]
+1 on this.
My nginx version installed correctly on the specified version of user specified version, but the path location give wrong version.
I also have read Noah's and Christine's before coming here.

How about moving all derived attributes into recipe based on Christine's workaround? I prefers that instead of delayed evaluation.

**Comment by tas50** [comment]
Thanks for opening this issue. Just today we merged the changes from the chef_nginx fork of this cookbook back to master here. It’s a pretty huge change set and includes over a year of active development that resulted in several major releases. I think there’s a very high chance that this issue has been resolved with that work and at this point I’m going to close this issue out. I’d encourage you to checkout the master branch and please open this issue back up if you’re still having the problem there.

Here’s the changes that were just merged in: https://github.com/chef-cookbooks/nginx/pull/435
