### ISSUE TITLE
Default nginx version on older Ubuntu

### ISSUE THREAD

**Issue by utilityboy** [chef-cookbooks/nginx#427]
Hi.  I've inherited a older chef project running `v2.7.4` of this cookbook that deploys nginx as a role:

roles['nginx'] looks like:

```
name "nginx"
description "Web Server"

run_list(
  "recipe[nginx]"
)

override_attributes(
  "nginx" => {
    "default_site_enabled" => false
  }
)
```

I would have expected this to install nginx 1.4.4 as that's what's specified here:

https://github.com/miketheman/nginx/blob/v2.7.4/attributes/default.rb#L26

But instead I get the Ubuntu 12.04.5 default version (`1.1.9`).

Any suggestions?  Do I need to wrap this in my own cookbook to get the expected behaviour?

Many thanks.

**Comment by miketheman** [comment]
Hi @utilityboy !

For the older, deprecated version of this cookbook, when specifying a version that is not part of the distro, you also need to specify how to install the desired binary.
See https://github.com/miketheman/nginx/blob/v2.7.4/attributes/default.rb#L102

If you select `source` instead, then the specified nginx version should be downloaded, compiled and installed per https://github.com/miketheman/nginx/blob/v2.7.4/recipes/source.rb

Otherwise, you'd have to specify a location (apt repo) where the package would be available, usually via an ``apt_repository` style resource.

**Comment by utilityboy** [comment]
Thanks for the information @miketheman.  

I'll adjust the role accordingly.

Given there are several servers already provisioned with this role, can you recommend the best way to update these existing nginx instances?

**Comment by miketheman** [comment]
@utilityboy It's hard to say what would be the right approach here - since the packages provided from nginx.org differ in structure than those provided from a Distribution (ubuntu, centos, etc) - in that the configs included are not 1-to-1, making this a riskier change.

I'd use a testing environment to test the upgrade path by passing in an `apt_repository` resource to get the nginx.org repos, and then upgrade the package, and see where the divergence lies before going to prod.

**Comment by tas50** [comment]
Thanks for opening this issue. Just today we merged the changes from the chef_nginx fork of this cookbook back to master here. It’s a pretty huge change set and includes over a year of active development that resulted in several major releases. I think there’s a very high chance that this issue has been resolved with that work and at this point I’m going to close this issue out. I’d encourage you to checkout the master branch and please open this issue back up if you’re still having the problem there.

Here’s the changes that were just merged in: https://github.com/chef-cookbooks/nginx/pull/435
